name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run PHP-CS-Fixer
        run: composer fix

      - name: Check code style
        run: composer check-style

      - name: Analyze code with PHPStan
        run: composer analyse

      - name: Run PHPUnit tests
        run: composer test
